/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato_hilos;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.applet.AudioClip;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.JOptionPane;
import sun.util.logging.PlatformLogger;
import static java.lang.Thread.sleep;
import java.util.Random;

public class Tablero extends javax.swing.JFrame implements Runnable {

    Random aleatorio = new Random(System.currentTimeMillis());
    FondoPanel fondo = new FondoPanel();
    // Musica music = new Musica();

    public int turno = 1;
    Thread h1;
    public int tempo = 3;
    public String matriz[][] = new String[3][3];

    int aleatorioFilas = 0;
    int aleatorioColumna = 0;
    int j1 = 1, j2 = 1, cont = 0;

    public Tablero() {
        initComponents();

        trasnparenciBoton();
        this.setLocationRelativeTo(null);
        Musica music = new Musica();
        music.start();
        h1 = new Thread(this);
        h1.start();
        this.player.setText("Jugador 1");
        this.setResizable(false);
        llenar();
        
    }

    public void trasnparenciBoton() {
        btn1.setOpaque(false);
        btn1.setContentAreaFilled(false);
        btn1.setBorderPainted(false);
        btn2.setOpaque(false);
        btn2.setContentAreaFilled(false);
        btn2.setBorderPainted(false);
        btn3.setOpaque(false);
        btn3.setContentAreaFilled(false);
        btn3.setBorderPainted(false);
        btn4.setOpaque(false);
        btn4.setContentAreaFilled(false);
        btn4.setBorderPainted(false);
        btn5.setOpaque(false);
        btn5.setContentAreaFilled(false);
        btn5.setBorderPainted(false);
        btn6.setOpaque(false);
        btn6.setContentAreaFilled(false);
        btn6.setBorderPainted(false);
        btn7.setOpaque(false);
        btn7.setContentAreaFilled(false);
        btn7.setBorderPainted(false);
        btn8.setOpaque(false);
        btn8.setContentAreaFilled(false);
        btn8.setBorderPainted(false);
        btn9.setOpaque(false);
        btn9.setContentAreaFilled(false);
        btn9.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        marcador1 = new javax.swing.JLabel();
        marcador2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tiempo = new javax.swing.JLabel();
        player = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn4.setPreferredSize(new java.awt.Dimension(63, 40));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setPreferredSize(new java.awt.Dimension(63, 40));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setPreferredSize(new java.awt.Dimension(63, 40));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn9.setPreferredSize(new java.awt.Dimension(63, 40));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn7.setPreferredSize(new java.awt.Dimension(63, 40));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn2.setPreferredSize(new java.awt.Dimension(63, 40));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn1.setPreferredSize(new java.awt.Dimension(63, 40));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn3.setPreferredSize(new java.awt.Dimension(63, 40));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Marcador");

        marcador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marcador1.setText("0");

        marcador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marcador2.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Tiempo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Turno:");

        tiempo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        player.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("J1:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("J2:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marcador1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcador2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(marcador1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(marcador2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(player, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        sonidoClick();
        if (turno == 1) {
            this.player.setText("Jugador 2");
            this.btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
            turno++;
            this.btn3.setEnabled(false);
            matriz[0][2] = "x";
            tempo = 5;
            verificar();
        } else if (turno == 2) {
            this.player.setText("Jugador 1");
            this.btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
            turno--;
            this.btn3.setEnabled(false);
            matriz[0][2] = "o";
            tempo = 5;
            verificar();
        }
        cont++;
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        sonidoClick();
        if (turno == 1) {
            this.player.setText("Jugador 2");
            this.btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
            turno++;
            this.btn4.setEnabled(false);
            matriz[1][0] = "x";
            tempo = 5;
            verificar();
        } else if (turno == 2) {
            this.player.setText("Jugador 1");
            this.btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
            turno--;
            this.btn4.setEnabled(false);
            matriz[1][0] = "o";
            tempo = 5;
            verificar();

        }
        cont++;
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        sonidoClick();
        if (turno == 1) {
            this.player.setText("Jugador 2");
            this.btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
            turno++;
            this.btn1.setEnabled(false);
            matriz[0][0] = "x";
            tempo = 5;
            verificar();
        } else if (turno == 2) {
            this.player.setText("Jugador 1");
            this.btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
            turno--;
            this.btn1.setEnabled(false);
            matriz[0][0] = "o";
            tempo = 5;
            verificar();
        }
        cont++;
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        sonidoClick();
        if (turno == 1) {
            this.player.setText("Jugador 2");
            this.btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
            turno++;
            this.btn2.setEnabled(false);
            matriz[0][1] = "x";
            tempo = 5;
            verificar();
        } else if (turno == 2) {
            this.player.setText("Jugador 1");
            this.btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
            turno--;
            this.btn2.setEnabled(false);
            matriz[0][1] = "o";
            tempo = 5;
            verificar();
        }
        cont++;
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        sonidoClick();
        if (turno == 1) {
            this.player.setText("Jugador 2");
            this.btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
            turno++;
            this.btn5.setEnabled(false);
            matriz[1][1] = "x";
            tempo = 5;
            verificar();
        } else if (turno == 2) {
            this.player.setText("Jugador 1");
            this.btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
            turno--;
            this.btn5.setEnabled(false);
            matriz[1][1] = "o";
            tempo = 5;
            verificar();
        }
        cont++;
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        sonidoClick();
        if (turno == 1) {
            this.player.setText("Jugador 2");
            this.btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
            turno++;
            this.btn6.setEnabled(false);
            matriz[1][2] = "x";
            tempo = 5;
            verificar();
        } else if (turno == 2) {
            this.player.setText("Jugador 1");
            this.btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
            turno--;
            this.btn6.setEnabled(false);
            matriz[1][2] = "o";
            tempo = 5;
            verificar();

        }
        cont++;
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        sonidoClick();
        if (turno == 1) {
            this.player.setText("Jugador 2");
            this.btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
            turno++;
            this.btn7.setEnabled(false);
            matriz[2][0] = "x";
            tempo = 5;
            verificar();
        } else if (turno == 2) {
            this.player.setText("Jugador 1");
            this.btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
            turno--;
            this.btn7.setEnabled(false);
            matriz[2][0] = "o";
            tempo = 5;
            verificar();
        }
        cont++;
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        sonidoClick();
        if (turno == 1) {
            this.player.setText("Jugador 2");
            this.btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
            turno++;
            this.btn8.setEnabled(false);
            matriz[2][1] = "x";
            tempo = 5;
            verificar();
        } else if (turno == 2) {
            this.player.setText("Jugador 1");
            this.btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
            turno--;
            this.btn8.setEnabled(false);
            matriz[2][1] = "o";
            tempo = 5;
            verificar();

        }
        cont++;
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        sonidoClick();
        if (turno == 1) {
            this.player.setText("Jugador 2");
            this.btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
            turno++;
            this.btn9.setEnabled(false);
            matriz[2][2] = "x";
            tempo = 5;
            verificar();

        } else if (turno == 2) {
            this.player.setText("Jugador 1");
            this.btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
            turno--;
            this.btn9.setEnabled(false);
            matriz[2][2] = "o";
            tempo = 5;
            verificar();
        }
        cont++;
    }//GEN-LAST:event_btn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marcador1;
    private javax.swing.JLabel marcador2;
    private javax.swing.JLabel player;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables

   

    public void verificar() {
        for (int i = 0; i < matriz.length; i++) {
            if (matriz[i][0].equals("x") && matriz[i][1].equals("x") && matriz[i][2].equals("x")) {
                sonidoWin();
                JOptionPane.showMessageDialog(null, "Ha ganado jugador 1");
                this.marcador1.setText(String.valueOf(j1++));
                reiniciar();
            }
            if (matriz[i][0].equals("o") && matriz[i][1].equals("o") && matriz[i][2].equals("o")) {
                sonidoWin();
                JOptionPane.showMessageDialog(null, "Ha ganado jugador 2");
                this.marcador2.setText(String.valueOf(j2++));
                reiniciar();
            }

        }
        for (int j = 0; j < matriz.length; j++) {
            if (matriz[0][j].equals("x") && matriz[1][j].equals("x") && matriz[2][j].equals("x")) {
                sonidoWin();
                JOptionPane.showMessageDialog(null, "Ha ganado jugador 1");
                this.marcador1.setText(String.valueOf(j1++));

                reiniciar();
            }
            if (matriz[0][j].equals("o") && matriz[1][j].equals("o") && matriz[2][j].equals("o")) {
                sonidoWin();
                JOptionPane.showMessageDialog(null, "Ha ganado jugador 2");
                this.marcador2.setText(String.valueOf(j2++));

                reiniciar();
            }
        }

        if ((matriz[1][1].equals("x") && matriz[2][2].equals("x") && matriz[0][0].equals("x")) || (matriz[0][2].equals("x") && matriz[1][1].equals("x") && matriz[2][0].equals("x"))) {
            sonidoWin();
            JOptionPane.showMessageDialog(null, "Ha ganado jugador 1");
            this.marcador1.setText(String.valueOf(j1++));

            reiniciar();
        }
        if ((matriz[1][1].equals("o") && matriz[2][2].equals("o") && matriz[0][0].equals("o")) || (matriz[0][2].equals("o") && matriz[1][1].equals("o") && matriz[2][0].equals("o"))) {
            sonidoWin();
            JOptionPane.showMessageDialog(null, "Ha ganado jugador 2");
            this.marcador2.setText(String.valueOf(j2++));
            reiniciar();
        }

        if (cont == 9) {
            JOptionPane.showMessageDialog(null, "Empate");
            reiniciar();
        }

    }

    public void llenar() {
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[i].length; j++) {
                matriz[i][j] = "";
            }
        }
    }

    public void sonidoWin() {
        try {
            new JFXPanel();
            String sonido = new File("equis.wav").toURI().toString();
            new MediaPlayer(new Media(sonido)).play();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void sonidoClick() {
        try {
            new JFXPanel();
            String sonido = new File("click.wav").toURI().toString();
            new MediaPlayer(new Media(sonido)).play();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void reiniciar() {
        this.btn1.setIcon(null);
        this.btn1.setEnabled(true);
        this.btn2.setIcon(null);
        this.btn2.setEnabled(true);
        this.btn3.setIcon(null);
        this.btn3.setEnabled(true);
        this.btn4.setIcon(null);
        this.btn4.setEnabled(true);
        this.btn5.setIcon(null);
        this.btn5.setEnabled(true);
        this.btn6.setIcon(null);
        this.btn6.setEnabled(true);
        this.btn7.setIcon(null);
        this.btn7.setEnabled(true);
        this.btn8.setIcon(null);
        this.btn8.setEnabled(true);
        this.btn9.setIcon(null);
        this.btn9.setEnabled(true);

        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz.length; j++) {
                matriz[i][j] = "-";
            }
        }

        turno = 1;
        cont = 0;

    }

    @Override
    public void run() {

        Thread ct = Thread.currentThread();
        while (ct == h1) {
            this.tiempo.setText(String.valueOf(tempo));
            tempo--;
            aleatorioColumna = aleatorio.nextInt(10) + 1;

            if (tempo < 0) {
                if (turno == 1) {
                    switch (aleatorioColumna) {
                        case 1:
                            this.player.setText("Jugador 2");
                            this.btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
                            turno++;
                            this.btn1.setEnabled(false);
                            matriz[0][0] = "x";
                            tempo = 5;
                            verificar();
                            break;
                        case 2:
                            this.player.setText("Jugador 2");
                            this.btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
                            turno++;
                            this.btn2.setEnabled(false);
                            matriz[0][1] = "x";
                            tempo = 5;
                            verificar();
                            break;
                        case 3:
                            this.player.setText("Jugador 2");
                            this.btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
                            turno++;
                            this.btn3.setEnabled(false);
                            matriz[0][2] = "x";
                            tempo = 5;
                            verificar();
                            break;
                        case 4:
                            this.player.setText("Jugador 2");
                            this.btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
                            turno++;
                            this.btn4.setEnabled(false);
                            matriz[1][0] = "x";
                            tempo = 5;
                            verificar();
                            break;
                        case 5:
                            this.player.setText("Jugador 2");
                            this.btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
                            turno++;
                            this.btn5.setEnabled(false);
                            matriz[1][1] = "x";
                            tempo = 5;
                            verificar();
                            break;
                        case 6:
                            this.player.setText("Jugador 2");
                            this.btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
                            turno++;
                            this.btn6.setEnabled(false);
                            matriz[1][2] = "x";
                            tempo = 5;
                            verificar();
                            
                            break;
                        case 7:
                            this.player.setText("Jugador 2");
                            this.btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
                            turno++;
                            this.btn7.setEnabled(false);
                            matriz[2][0] = "x";
                            tempo = 5;
                            verificar();
                            break;
                        case 8:
                            this.player.setText("Jugador 2");
                            this.btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
                            turno++;
                            this.btn8.setEnabled(false);
                            matriz[2][1] = "x";
                            tempo = 5;
                            verificar();
                            break;
                        case 9:
                            this.btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equis png.png")));
                            turno++;
                            this.btn9.setEnabled(false);
                            matriz[2][2] = "x";
                            tempo = 5;
                            verificar();
                            break;

                    }
                } else {
                    switch (aleatorioColumna) {
                        case 1:
                            this.player.setText("Jugador 1");
                            this.btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
                            turno--;
                            this.btn1.setEnabled(false);
                            matriz[0][0] = "o";
                            tempo = 5;
                            verificar();
                            break;
                        case 2:
                            this.btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
                            turno--;
                            this.btn2.setEnabled(false);
                            matriz[0][1] = "o";
                            tempo = 5;
                            verificar();
                            break;
                        case 3:
                            this.btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
                            turno--;
                            this.btn3.setEnabled(false);
                            matriz[0][2] = "o";
                            tempo = 5;
                            verificar();
                            break;
                        case 4:
                            this.btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
                            turno--;
                            this.btn4.setEnabled(false);
                            matriz[1][0] = "o";
                            tempo = 5;
                            verificar();
                            break;
                        case 5:
                            this.btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
                            turno--;
                            this.btn5.setEnabled(false);
                            matriz[1][1] = "o";
                            tempo = 5;
                            verificar();
                            break;
                        case 6:
                            this.btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
                            turno--;
                            this.btn6.setEnabled(false);
                            matriz[1][2] = "o";
                            tempo = 5;
                            verificar();
                            break;
                        case 7:
                            this.btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
                            turno--;
                            this.btn7.setEnabled(false);
                            matriz[2][0] = "o";
                            tempo = 5;
                            verificar();
                            break;
                        case 8:
                            this.btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
                            turno--;
                            this.btn8.setEnabled(false);
                            matriz[2][1] = "o";
                            tempo = 5;
                            verificar();
                            break;
                        case 9:
                            this.btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circulo png.png")));
                            turno--;
                            this.btn9.setEnabled(false);
                            matriz[2][2] = "o";
                            tempo = 5;
                            verificar();
                            break;

                    }
                }
            }
            try {
                sleep(1000); //System.out.println(e);  
            } catch (Exception e) {
                Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, e);

            }

        }

        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

    }

    

}

class FondoPanel extends JPanel {

    private Image imagen;

    @Override

    public void paint(Graphics g) {

        imagen = new ImageIcon(getClass().getResource("/Imagenes/Tablero.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);

        super.paint(g);
    }
}
